---
title: 'Coronavirus en Mexico (Series de Tiempo)'
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll

---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.align = 'center',
                      fig.width = 12,
                      fig.height = 8)

library(tidyverse)
library(tsibble)
library(feasts)
library(fable)
library(flexdashboard)
library(devtools)
install_github('RamiKrispin/coronavirus', force = TRUE)
library(coronavirus)
update_dataset(silence = TRUE)
data(coronavirus)

df_daily <- coronavirus %>%
  filter(country == 'Mexico') %>%
  filter(date > '2020-02-26') %>%
  group_by(date, type) %>%
  summarise(total = sum(cases,
                        na.rm = TRUE)) %>%
  pivot_wider(names_from = type,
              values_from = total) %>%
  arrange(date) %>%
  ungroup() %>%
  as_tsibble(index = date) %>%
  fill_gaps(Casos = 0L)
```


Casos confirmados
=======================================================================
  
Column
-----------------------------------------------------------------------
  
```{r casos decompose}
df_daily %>%
  model(STL(confirmed ~ season(period = 7))) %>%
  components() %>%
  rename(Fecha = date,
         Casos = confirmed,
         Tendencia = trend,
         Ciclos = season_7,
         Ruido = remainder) %>%
  select(Fecha,
         Casos,
         Tendencia,
         Ciclos,
         Ruido) %>%
  pivot_longer(cols = Casos:Ruido,
               names_to = 'Serie') %>%
  ggplot(aes(Fecha, value)) +
  geom_line() +
  facet_grid(Serie ~ .,
             scales = 'free_y') +
  labs(title = 'Casos diarios (componentes)',
       x = 'Semana',
       y = 'Muertes')
```

```{r casos forecast}
df_daily %>%
  model(arima = ARIMA(confirmed)) %>%
  forecast() %>%
  autoplot(filter(df_daily,
                  date > '2020-02-26')) +
  labs(title = 'Casos diarios (predicciones)',
       x = 'Semana',
       y = 'Muertes',
       level = 'Nivel')
```


Muertes
=======================================================================
  
Column
-----------------------------------------------------------------------

```{r muertes decompose}
df_daily %>%
  model(STL(death ~ season(period = 7))) %>%
  components() %>%
  rename(Fecha = date,
         Casos = death,
         Tendencia = trend,
         Ciclos = season_7,
         Ruido = remainder) %>%
  select(Fecha, Casos, Tendencia, Ciclos, Ruido) %>%
  pivot_longer(cols = Casos:Ruido,
               names_to = 'Serie') %>%
  ggplot(aes(Fecha, value)) +
  geom_line() +
  facet_grid(Serie ~ .,
             scales = 'free_y') +
  labs(title = 'Muertes diarias (componentes)',
       x = 'Semana',
       y = 'Muertes')
```

```{r muertes forecast}
df_daily %>%
  model(arima = ARIMA(death)) %>%
  forecast() %>%
  autoplot(filter(df_daily,
                  date > '2020-03-17')) +
  labs(title = 'Muertes diarias (predicciones)',
       x = 'Semana',
       y = 'Muertes',
       level = 'Nivel')
```

Código y fuentes
=======================================================================

Column
-----------------------------------------------------------------------

Autor: Jorge Ortega

**Codigo**
  
Disponible en [GitHub](https://github.com/jisaaco/corona/blob/master/CoronaMexTS.Rmd){target='_blank'}.

**Datos sobre el coronavirus**
  
Disponibles en [`{coronavirus}`](https://github.com/RamiKrispin/coronavirus){target='_blank'}.

Datos crudos del Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE) Coronavirus [repository](https://github.com/RamiKrispin/coronavirus-csv){target='_blank'}.
