---
title: 'Coronavirus en Quintana Roo'
author: 'Jorge Ortega'
output:
  html_document:
    df_print: paged
---

**Codigo**
  
Disponible en [GitHub](https://github.com/jisaaco/corona/blob/master/CoronaYuc.Rmd){target='_blank'}.

**Datos sobre el coronavirus**
  
Disponibles en [Dirección General de Epidemología](https://www.gob.mx/salud/documentos/datos-abiertos-152127){target='_blank'}.

```{r paquetes y base, include = FALSE}
knitr::opts_chunk$set(fig.align = 'center',
                      fig.width = 12,
                      fig.height = 8,
                      echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(tsibble)
library(feasts)
library(fable)

temp <- tempfile()
download.file('http://187.191.75.115/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip', temp)
file.rename(unzip(temp), 'COVIDMEX.csv')
remove(temp)

COVIDMEX <- read_csv('COVIDMEX.csv')

### Bases de datos

sick <- COVIDMEX %>%
  filter(ENTIDAD_RES == 23,
         RESULTADO == 1) %>%
  select(FECHA_SINTOMAS) %>%
  group_by(FECHA_SINTOMAS) %>%
  summarise(Casos = n()) %>%
  as_tsibble(index = FECHA_SINTOMAS) %>%
  fill_gaps(Casos = 0L)

dead <- COVIDMEX %>%
  filter(ENTIDAD_RES == 23,
         RESULTADO == 1,
         !is.na(FECHA_DEF)) %>%
  select(FECHA_DEF) %>%
  group_by(FECHA_DEF) %>%
  summarise(Casos = n()) %>%
  as_tsibble(index = FECHA_DEF) %>%
  fill_gaps(Casos = 0L)
```

```{r tendencia casos}
sick %>%
  ggplot(aes(FECHA_SINTOMAS, Casos)) +
  geom_line() +
  geom_smooth() +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  labs(x = 'Fecha',
       y = 'Nuevos casos diarios') +
  ggtitle('Casos confirmados diarios (tendencia)')
```

```{r series casos 1}
sick %>%
  model(STL(Casos ~ season(period = 7))) %>%
  components() %>%
  rename(Fecha = FECHA_SINTOMAS,
         Casos = Casos,
         Tendencia = trend,
         Ciclos = season_7,
         Ruido = remainder) %>%
  select(Fecha, Casos, Tendencia, Ciclos, Ruido) %>%
  pivot_longer(cols = Casos:Ruido,
               names_to = 'Serie') %>%
  ggplot(aes(Fecha, value)) +
  geom_line() +
  facet_grid(Serie ~ .,
             scales = 'free_y') +
  labs(title = 'Casos confirmados diarios (componentes)',
       x = 'Semana',
       y = 'Casos')
```

```{r series casos 2}
sick %>%
  model(arima = ARIMA(Casos)) %>%
  forecast() %>%
  autoplot(
    filter(
      sick,
      FECHA_SINTOMAS > '2020-03-06'
      )) +
   labs(title = 'Casos confirmados diarios (predicciones)',
       x = 'Semana',
       y = 'Casos',
       level = 'Nivel')
```

```{r tendencias muertes}
dead %>%
  ggplot(aes(FECHA_DEF, Casos)) +
  geom_line() +
  geom_smooth() +
  scale_y_continuous(breaks = seq(0, 10, 1)) +
  labs(title = 'Nuevas muertes diarias (tendencia)',
       x = 'Semana',
       y = 'Muertes')
```

```{r series muertes 1}
dead %>%
  model(STL(Casos ~ season(period = 7))) %>%
  components() %>%
  rename(Fecha = FECHA_DEF,
         Casos = Casos,
         Tendencia = trend,
         Ciclos = season_7,
         Ruido = remainder) %>%
  select(Fecha, Casos, Tendencia, Ciclos, Ruido) %>%
  pivot_longer(cols = Casos:Ruido,
               names_to = 'Serie') %>%
  ggplot(aes(Fecha, value)) +
  geom_line() +
  facet_grid(Serie ~ .,
             scales = 'free_y') +
  labs(title = 'Nuevas muertes diarias (componentes)',
       x = 'Semana',
       y = 'Muertes')
```

```{r series muertes 2}
dead %>%
  model(arima = ARIMA(Casos)) %>%
  forecast() %>%
  autoplot(
    filter(
      dead,
      FECHA_DEF > '2020-04-02'
      )) +
  labs(title = 'Nuevas muertes diarias (predicciones)',
       x = 'Semana',
       y = 'Muertes',
       level = 'Nivel')
```
