---
title: 'Coronavirus en Mexico'
output: flexdashboard::flex_dashboard

---
  
```{r setup, include=FALSE}
#------------------ Packages ------------------
library(tidyverse)
library(flexdashboard)
library(devtools)
library(coronavirus)
library(scales)
library(ggdark)
update_dataset(silence = TRUE)
data(coronavirus)

#------------------ Data ------------------
df <- coronavirus %>%
  filter(country == 'Mexico') %>%
  filter(date > '2020-02-26') %>%
  group_by(country, type) %>%
  summarise(total = sum(cases)) %>%
  pivot_wider(
    names_from = type,
    values_from = total
  ) %>%
  mutate(unrecovered = confirmed - ifelse(is.na(death), 0, death)) %>%
  arrange(-confirmed) %>%
  ungroup()

df_daily <- coronavirus %>%
  filter(country == 'Mexico') %>%
  filter(date > '2020-02-26') %>%
  group_by(date, type) %>%
  summarise(total = sum(cases, na.rm = TRUE)) %>%
  pivot_wider(
    names_from = type,
    values_from = total
  ) %>%
  arrange(date) %>%
  ungroup() %>%
  mutate(active = confirmed - death) %>%
  mutate(
    confirmed_cum = cumsum(confirmed),
    death_cum = cumsum(death),
    death_cum_per = death_cum / confirmed_cum * 100,
    active_cum = cumsum(active)
  )

daily_confirmed <- coronavirus %>%
  filter(type == 'confirmed') %>%
  filter(date >= '2020-02-29') %>%
  mutate(country = country) %>%
  group_by(date, country) %>%
  summarise(total = sum(cases)) %>%
  ungroup() %>%
  pivot_wider(names_from = country, values_from = total)

df1 <- coronavirus %>% filter(date == max(date))
```

Casos acumulados
=======================================================================
  
Column
-----------------------------------------------------------------------
  
### **Casos acumulados en Mexico (log 10)**
  
```{r}
df_daily %>%
  ggplot(aes(date, confirmed_cum)) + 
  geom_line() +
  geom_smooth() +
  scale_y_log10(breaks = trans_breaks("log10",
                                      function(x) 10^x),
                                      labels = trans_format("log10", math_format(10^.x))) +
  labs(x = 'Fecha',
       y = 'Numero acumulado de casos') +
  annotation_logticks() +
  dark_mode()
```


Muertes acumuladas
=======================================================================
  
Column
-----------------------------------------------------------------------
  
### **Muertes acumuladas en Mexico (log 10)**
  
```{r}
df_daily %>%
  ggplot(aes(date, death_cum)) + 
  geom_line() +
  geom_smooth() +
  scale_y_log10(breaks = trans_breaks("log10",
                                      function(x) 10^x),
                                      labels = trans_format("log10", math_format(10^.x))) +
  labs(x = 'Fecha',
       y = 'Numero acumulado de muertes') +
  annotation_logticks() +
  dark_mode()
```


Nuevos casos
=======================================================================
  
Column
-------------------------------------
  
### **Nuevos casos diarios**
  
```{r}
daily_confirmed %>%
  ggplot(aes(date, Mexico / 1000)) +
  geom_line() +
  geom_smooth() +
  scale_y_continuous(breaks = seq(0, 3, 0.2)) +
  labs(x = 'Fecha',
       y = 'Nuevos casos diarios (miles)') +
  dark_mode()  
```


Tasa de muertes
=======================================================================
  
Column
-------------------------------------
  
  
### **Tasa de muertes (%)**
  
```{r}
df_daily %>%
  ggplot(aes(date, death_cum_per)) +
  geom_line() +
  geom_smooth() +
  scale_y_continuous(breaks = seq(0, 12, 1)) +
  labs(x = 'Fecha',
       y = 'Tasa de muertes (%)') +
  dark_mode()
```

Resumen y fuentes
=======================================================================

Column
-----------------------------------------------------------------------
  
### confirmed {.value-box}

```{r}

valueBox(
  value = paste(format(sum(df$confirmed), big.mark = ','), '', sep = ' '),
  caption = 'Casos totales confirmados [Primer caso: 27 de Febrero]',
  color = 'steelblue'
)
```


### death {.value-box}

```{r}

valueBox(
  value = paste(format(sum(df$death, na.rm = TRUE), big.mark = ','), ' (',
                round(100 * sum(df$death, na.rm = TRUE) / sum(df$confirmed), 1),
                '%)',
                sep = ''
  ),
  caption = 'Muertes (tasa) [Primera muerte: 18 de Marzo]',
  color = 'darkred'
)
```



Column
-------------------------------------

Autor: Jorge Ortega

**Codigo**
  
Disponible en [GitHub](https://github.com/jisaaco/corona/blob/master/CoronaMex.Rmd){target='_blank'}.

**Datos sobre el coronavirus**
  
Disponibles en [`{coronavirus}`](https://github.com/RamiKrispin/coronavirus){target='_blank'}.

Datos crudos del Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE) Coronavirus [repository](https://github.com/RamiKrispin/coronavirus-csv){target='_blank'}.
